### ISSUE TITLE
Roles on Messages

### ISSUE THREAD

**Issue by GabCores** [minimaxir/simpleaichat#13]
Hi , I have a prompt that have been defined as SYSTEM , USER and ASSISTANCE roles .
In the OpenAI playground any alteration of the content for each role, give undesired results .
Was not able to find how to configure roles in this library 
May you help me ?

Nice job !

**Comment by minimaxir** [comment]
The documentation isn't there yet, but you can manually set messages starting a conversation:

```py3
from simpleaichat import AIChat
from simpleaichat.models import ChatMessage

message1 = ChatMessage(role="user", content="Do a thing.")
message2 = ChatMessage(role="assistant", content="I did a thing.")

ai = AIChat(console=False)
ai.default_session.messages = [message1, message2]
```

Unclear if that answers your question. Doing anything with roles beyond that is not recommended.

**Comment by GabCores** [comment]
Ok ! I was searching for that . 
waiting the best . regards !

**Comment by keyboardAnt** [comment]
> The documentation isn't there yet, but you can manually set messages starting a conversation:
> 
> ```python
> from simpleaichat import AIChat
> from simpleaichat.models import ChatMessage
> 
> message1 = ChatMessage(role="user", content="Do a thing.")
> message2 = ChatMessage(role="assistant", content="I did a thing.")
> 
> ai = AIChat(console=False)
> ai.default_session.messages = [message1, message2]
> ```
> 
> Unclear if that answers your question. Doing anything with roles beyond that is not recommended.

How can I print the final string sent to the API? 
Thanks!

**Comment by minimaxir** [comment]
@keyboardAnt What use case is there for that? The only thing really sent to the API is what is provided to the `prompt`, wrapped as a `ChatMessage` as above, along with previous messages.

**Comment by keyboardAnt** [comment]
> @keyboardAnt What use case is there for that? The only thing really sent to the API is what is provided to the `prompt`, wrapped as a `ChatMessage` as above, along with previous messages.

Thanks for replying!
For debugging, answering your question.

**Comment by minimaxir** [comment]
For debugging you can use `prepare_request()` which constructs the data to be sent to the ChatGPT API, e.g.

```py3
ai.default_session.prepare_request(prompt)[1]
```

Which returns the full set of `data` used as model parameters.

That should get covered in more formal documentation. Once a full logging/debugging flow is added I may add that to it.

This is getting off topic, so closing.
