### ISSUE TITLE
Does it support it caching?

### ISSUE THREAD

**Issue by OnlinePage** [minimaxir/simpleaichat#2]
Hi, very nice library ,especially it is light. Does it support caching, so that the api calls can be reduced? just like Gpt-cache or else

**Comment by minimaxir** [comment]
Something like GPTCache is definitely not simple and would not be implemented natively.

From reading the README, a vector store for checking existing inputs and caching them can be done externally too.

**Comment by minimaxir** [comment]
None of that needs to be in the library proper.

If caching inputs is that important of a use case, I can make a demo of it at some point.
