### ISSUE TITLE
Prioritize passed parameter over env variable

### ISSUE THREAD

**Issue by AsafMah** [minimaxir/simpleaichat#20]
Basically
instead of this
`            gpt_api_key = os.getenv("OPENAI_API_KEY") or kwargs.get("api_key")`

this

`            gpt_api_key = kwargs.get("api_key") or os.getenv("OPENAI_API_KEY")`

Params are more specific than env variable, and this behaviour was unexpected (to me)

**Comment by minimaxir** [comment]
This wasn't a situation I would expect to happen, but yes was changed for consistency.
