### ISSUE TITLE
Support requests with `input_schema` and previous `messages`?

### ISSUE THREAD

**Issue by keyboardAnt** [minimaxir/simpleaichat#32]
It [seems](https://github.com/minimaxir/simpleaichat/blob/d8f04a5c0414356337beb0c392236ee48c38b865/simpleaichat/chatgpt.py#L50) like requests with `input_schema` overwrite the `messages` history. Why limit requests such that `messages == [system_msg, user_msg_with_input_schema]`?

**Comment by minimaxir** [comment]
`self.format_input_messages()` uses [the entire message history](https://github.com/minimaxir/simpleaichat/blob/d8f04a5c0414356337beb0c392236ee48c38b865/simpleaichat/models.py#L78-L79) and the line linked is not conditional on `input_schema`.
