### ISSUE TITLE
Support unsafe function schemas

### ISSUE THREAD

**Issue by keyboardAnt** [minimaxir/simpleaichat#38]
LLMs for code are capable of reasoning beyond just what is merely executable [^1][^2]. Therefore, I suggest [allowing](https://github.com/minimaxir/simpleaichat/blob/1dead657731e0d2a4df608a7aa94b86322412851/simpleaichat/chatgpt.py#L62) users to provide free-form function schemas that aren't necessarily strictly following the JSON Schema format.

[^1]: Souza, Beatriz, and Michael Pradel. "LExecutor: Learning-Guided Execution." arXiv preprint arXiv:2302.02343 (2023).
[^2]: https://www.youtube.com/watch?v=YIYlkCbIxqc&t=2664s

**Comment by minimaxir** [comment]
Function input implementation is handled by a model-by-model basis, which is why the current schema code is in `chatgpt.py`.

**Comment by keyboardAnt** [comment]
@minimaxir, what do you mean by "model-by-model basis"?

**Comment by minimaxir** [comment]
This implementation of structured I/O to ChatGPT is specific to ChatGPT.

**Comment by keyboardAnt** [comment]
Okay, but why not allow users to provide schemas that violate the JSON Schema format?

**Comment by minimaxir** [comment]
No point, unless there is evidence that it actually improves generation quality.

To keep the library simple, I am not adding things for the sake of adding things.
