### ISSUE TITLE
Buggy? - Calling to `string.json()`

### ISSUE THREAD

**Issue by keyboardAnt** [minimaxir/simpleaichat#39]
Does `prepare_request`'s [`prompt`](https://github.com/minimaxir/simpleaichat/blob/1dead657731e0d2a4df608a7aa94b86322412851/simpleaichat/chatgpt.py#L44) a string?

**Comment by minimaxir** [comment]
Yes, it's a minified JSON string. In Pydantic v2.0 it's renamed to `model_dump_json` to be more clear.

**Comment by keyboardAnt** [comment]
Not every string has a `.json()` method, so perhaps we want to specifically indicate the [type](https://github.com/minimaxir/simpleaichat/blob/1dead657731e0d2a4df608a7aa94b86322412851/simpleaichat/chatgpt.py#L23) of `prompt`?

**Comment by minimaxir** [comment]
The conditional flow is on `input_schema` so it will _always_ correspond to a Pydantic object. Unfortunately there's no good type hint for a Pydantic object.
