### ISSUE TITLE
Will Simpleaichat support embedding?

### ISSUE THREAD

**Issue by flyq** [minimaxir/simpleaichat#64]
According to here: https://github.com/minimaxir/simpleaichat/issues/25#issuecomment-1600048436
> (and to be clear nothing in simpleaichat is working with embeddings)

So, Will Simpleaichat support embedding?

**Comment by minimaxir** [comment]
Embeddings are a broad topic in the AI ecosystem, but simpleaichat will not be natively supporting anything involving embeddings.

There may be demos involving vector stores but nothing native to the library itself, since there's no reason to make it inherent to the library.
