### ISSUE TITLE
Too many line breaks in Jupyter Lab / Notebook

### ISSUE THREAD

**Issue by zeitderforschung** [minimaxir/simpleaichat#66]
Printing every object line by line seems to be the default behaviour of the rich console, because the JupyterMixin in rich uses [IPython.display](https://github.com/Textualize/rich/blob/720800e6930d85ad027b1e9bd0cbb96b5e994ce3/rich/jupyter.py#L91) which is not suited for the streaming use case.

<img width="552" alt="image" src="https://github.com/minimaxir/simpleaichat/assets/54367033/12106caa-e689-4080-a1d6-42a753bda47d">

The behaviour can be fixed with **force_jupyter=False**:

```python
def interactive_console(self, character: str = None, prime: bool = True) -> None:
    console = Console(highlight=False, force_jupyter=False)
```

<img width="566" alt="image" src="https://github.com/minimaxir/simpleaichat/assets/54367033/df71de6b-4f1b-49c3-ad44-a2216562244e">

**Comment by minimaxir** [comment]
LGTM. Thanks! :)
