### ISSUE TITLE
Support for LLama and Hugging Face models?

### ISSUE THREAD

**Issue by sysadminpower2019** [minimaxir/simpleaichat#81]
Is this currently supported?

**Comment by minimaxir** [comment]
Not currently; it's in the pipeline for investigation, but there's no way to make it "simple" because there's a very large number of software and hardware constraints so it's not a trivial task.

**Comment by sysadminpower2019** [comment]
is there a way to use the simpleaichat then without a chatgpt / openai api key? I would rather not feed the OpenAI monster even more data, if we can instead find a way to self host things

**Comment by adrianog** [comment]
can you not use a adapter to adapt hf models to OAI interface?
