### ISSUE TITLE
has this been abandoned? 

### ISSUE THREAD

**Issue by SAI-sentinal-ai** [minimaxir/simpleaichat#91]
as title

**Comment by HerrIvan** [comment]
With all due respect, I am also interested in the answer.

**Comment by minimaxir** [comment]
No, I had a mental breakdown and had to step away for a bit.

Work is resuming, but again this project is tightly scoped and will not be as vibrant as related AI projects, so some inactivity doesn't mean it's dead.

**Comment by SAI-sentinal-ai** [comment]
Sorry to hear about your issues. Thanks for all the work. Get well soon.
